### PR TITLE
BDS-17 - NICC API : Upgrade the service to use HIP token

### PR DESCRIPTION
**Pull request by MartinTGeorgiev**
Upgrade the service to use HIP token

### CODE REVIEW

**Review by martin-adaramola — APPROVED** [review]

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by martin-adaramola** [comment]
Test this please.

**Comment by martin-adaramola** [comment]
Test this please.

**Pull request merged**
