### PR TITLE
BDS-17 : NICC API : Upgrade the service to use HIP token

### PR DESCRIPTION
**Pull request by MartinTGeorgiev**
Disabled JUnitXmlReportPlugin to resolve Unstable build/deployment.

### CODE REVIEW

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Review by lachmand — DISMISSED** [review]

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please

**Review by martin-adaramola — APPROVED** [review]

**Pull request merged**
