### PR TITLE
BDS-102 : Deploy to External Test

### PR DESCRIPTION
**Pull request by MartinTGeorgiev**
Removed unused comment

### CODE REVIEW

**Review by martin-adaramola — APPROVED** [review]

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Comment by MartinTGeorgiev** [comment]
Test this please.

**Pull request merged**
